[application]
name = "tensorrt-converter"
default_platform = "fullstack"
asset_dir = "assets"

[web.app]
title = "TensorRT Converter"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []
