name: "$MODEL_NAME"
platform: "tensorrt_plan"

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

#dynamic_batching {
#  preferred_batch_size: [ 4, 8 ]
#  max_queue_delay_microseconds: 100
#}

#max_batch_size: 8

model_warmup {                                                                        
    name: "$MODEL_NAME"  
    inputs: $INPUT_WARMUP_BLOCKS                                                    
}

input [
$INPUT_BLOCKS
]

output [
$OUTPUT_BLOCKS
]
