name: "model"
platform: "tensorrt_plan"
max_batch_size: 2

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 512, 512 ]
  }
]

output [
  {
    name: "masks"
    data_type: TYPE_FP32
    dims: [ -1, 512, 512 ]
  }
]

dynamic_batching { }
